import type { Choice, ProductResponse, StudyInfo, Summary } from '../types'

/** One base URL: the product webhook. The other webhooks of the n8n "scelte"
 *  workflow live next to it, so they are derived, not configured. */
const PRODUCT_URL = import.meta.env.VITE_N8N_WEBHOOK_URL as string | undefined
const base = () => (PRODUCT_URL ?? '').replace(/photo-lab-product\/?$/, '')

/** The published site may outlive the backend (n8n trial, laptop off). Studio and
 *  Esperimento then read a frozen copy written by experiments/scripts/export_snapshot.py;
 *  Prova needs the live backend and says so. */
const SNAPSHOT = `${import.meta.env.BASE_URL}snapshot/`
let usingSnapshot = false

export function isLiveConfigured(): boolean {
  return Boolean(PRODUCT_URL)
}

/** True once a lab view had to fall back to the frozen copy. */
export function isSnapshotMode(): boolean {
  return usingSnapshot
}

async function liveOrSnapshot<T>(live: () => Promise<T>, snapshotPath: string): Promise<T> {
  if (PRODUCT_URL) {
    try {
      const value = await live()
      usingSnapshot = false
      return value
    } catch {
      /* fall through to the frozen copy */
    }
  }
  const res = await fetch(SNAPSHOT + snapshotPath)
  if (!res.ok) throw new Error('backend non raggiungibile e nessuna copia statica disponibile')
  usingSnapshot = true
  return (await res.json()) as T
}

async function getJson<T>(url: string): Promise<T> {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`n8n ha risposto ${res.status}`)
  return (await res.json()) as T
}

/** One upload. The webhook answers at once with the job id; the three versions
 *  are fetched by polling (the generative model can take two minutes when cold,
 *  longer than n8n Cloud keeps a webhook open). */
export async function runProduct(file: File, onProgress?: (elapsedMs: number) => void, signal?: AbortSignal): Promise<ProductResponse> {
  if (!PRODUCT_URL) throw new Error('VITE_N8N_WEBHOOK_URL non configurato')
  const form = new FormData()
  form.append('image', file)
  const res = await fetch(PRODUCT_URL, { method: 'POST', body: form, signal })
  if (!res.ok) throw new Error(`n8n ha risposto ${res.status}`)
  const { image_id } = (await res.json()) as { image_id: string }
  try {
    sessionStorage.setItem('photo-lab:pending', JSON.stringify({ image_id, t0: Date.now() }))
  } catch {
    /* storage unavailable: no resume after reload */
  }
  return waitForResult(image_id, onProgress, signal)
}

/** Poll until the record is saved. Also used to resume after a page reload. */
export async function waitForResult(image_id: string, onProgress?: (elapsedMs: number) => void, signal?: AbortSignal): Promise<ProductResponse> {
  const t0 = Date.now()
  for (;;) {
    const poll = await fetch(`${base()}photo-lab-result?image_id=${encodeURIComponent(image_id)}`, { signal })
    if (poll.ok) {
      const body = (await poll.json()) as ProductResponse & { ready: boolean }
      if (body.ready) {
        try {
          sessionStorage.removeItem('photo-lab:pending')
        } catch {
          /* ignore */
        }
        return body
      }
    }
    await new Promise((r) => setTimeout(r, 5000))
    onProgress?.(Date.now() - t0)
    if (Date.now() - t0 > 6 * 60 * 1000) throw new Error('nessun risultato dopo 6 minuti')
  }
}

/** An upload started before a reload, if any. */
export function pendingUpload(): { image_id: string; t0: number } | null {
  try {
    const raw = sessionStorage.getItem('photo-lab:pending')
    return raw ? (JSON.parse(raw) as { image_id: string; t0: number }) : null
  } catch {
    return null
  }
}

/** The agent's blind choice: the one measurement the experiment is built on.
 *  Returns false when it could not be recorded (snapshot mode). */
export async function sendChoice(choice: Choice): Promise<boolean> {
  if (!PRODUCT_URL || usingSnapshot) return false
  try {
    const res = await fetch(`${base()}photo-lab-choice`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(choice),
    })
    return res.ok
  } catch {
    return false
  }
}

export function fetchSummary(): Promise<Summary> {
  return liveOrSnapshot(() => getJson<Summary>(`${base()}photo-lab-summary`), 'summary.json')
}

/** The blind study: which photos, which are ready, who has already taken it. */
export function fetchStudy(): Promise<StudyInfo> {
  return liveOrSnapshot(() => getJson<StudyInfo>(`${base()}photo-lab-study`), 'study.json')
}

/** The three versions of one study photo (already generated by the batch). */
export async function fetchResult(imageId: string): Promise<ProductResponse | null> {
  const body = await liveOrSnapshot(
    () => getJson<ProductResponse & { ready: boolean }>(`${base()}photo-lab-result?image_id=${encodeURIComponent(imageId)}`),
    `cards/${imageId}.json`,
  )
  if (!body.ready) return null
  // the frozen copy stores relative image paths instead of data URLs
  const abs = (p: string | null) => (p && !p.startsWith('data:') ? import.meta.env.BASE_URL + p : p)
  return { ...body, original: abs(body.original), cards: body.cards.map((c) => ({ ...c, output: abs(c.output) })) }
}
